name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install Dependencies
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: Run all workspace
        run: pnpm run test

      - name: Run test workspace case-1-noStrict
        run: pnpm run test --project case-1-noStrict

      - name: Run test workspace case-1
        run: pnpm run test --project case-1
